@startuml
skinparam backgroundColor White
title Microservices Component Diagram

package "Edge" {
  [API Gateway :7777] as Gateway
  [React Frontend] as Frontend
  Gateway <--> Frontend : "REST HTTP"
}

package "Identity" {
  component ".NET Identity\n:7002" as IdentitySvc
  Gateway <--> IdentitySvc : "auth"
}

package "Store" {
  component "Product Service\n:7000" as Product
  component "Coupon Service\n:7001" as Coupon
  component "ShoppingCart Service\n:7003" as Cart
  component "Order Service\n:7004" as Order
  component "Email Service" as Email
  component "Rewards Service" as Rewards
}

[Service Bus] as Bus

Product <--> Bus
Coupon <--> Bus
Cart <--> Bus
Order <--> Bus
Email <--> Bus 
Rewards <--> Bus

Gateway <--> Product
Gateway <--> Cart
Gateway <--> Order
@enduml